services:
  api:
    build: .
    container_name: furniture_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - furniture-net

  db:
    image: postgres:15
    container_name: furniture_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=furniture_user
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=furniture_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - furniture-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: furniture_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - furniture-net

networks:
  furniture-net:
    driver: bridge

volumes:
  postgres_data:
