"""Add default to updated_at

Revision ID: 5c9aad8f4ea2
Revises: 659b229fa25c
Create Date: 2025-11-21 14:15:16.507335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9aad8f4ea2'
down_revision: Union[str, None] = '659b229fa25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
