"""Add Furniture Product Fields

Revision ID: 659b229fa25c
Revises: 314e009ed192
Create Date: 2025-11-21 14:04:31.139317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '659b229fa25c'
down_revision: Union[str, None] = '314e009ed192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.drop_index('ix_product_images_id', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_addresses_user_default', table_name='addresses')
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.drop_column('categories', 'display_order')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'is_active')
    op.add_column('products', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('specs', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # Replaced alter_column with drop/add to avoid casting errors
    op.drop_column('products', 'dimensions')
    op.add_column('products', sa.Column('dimensions', sa.JSON(), nullable=True))
    
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'products', 'collections', ['collection_id'], ['id'])
    op.drop_column('products', 'discount_percent')
    op.drop_column('products', 'color')
    op.drop_column('products', 'sales_count')
    op.drop_column('products', 'views_count')
    op.drop_column('products', 'material')
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sales_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'dimensions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('products', 'collection_id')
    op.drop_column('products', 'specs')
    op.drop_column('products', 'images')
    op.drop_column('products', 'thumbnail_url')
    op.drop_column('products', 'sale_price')
    op.add_column('categories', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('categories', 'parent_id')
    op.create_index('ix_addresses_user_default', 'addresses', ['user_id', 'is_default'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_images_pkey')
    )
    op.create_index('ix_product_images_id', 'product_images', ['id'], unique=False)
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
