"""add_sale_price_to_collections

Revision ID: 793ad2b0e949
Revises: 06394a308c0d
Create Date: 2025-12-01 13:20:27.989428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793ad2b0e949'
down_revision: Union[str, None] = '06394a308c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('sale_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'sale_price')
    # ### end Alembic commands ###
