"""Refactor Order model for Furniture business

Revision ID: 83633d33f361
Revises: 5c9aad8f4ea2
Create Date: 2025-11-21 16:43:43.818920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83633d33f361'
down_revision: Union[str, None] = '5c9aad8f4ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_at_purchase', sa.Float(), nullable=False))
    op.add_column('order_items', sa.Column('variant', sa.String(), nullable=True))
    op.drop_column('order_items', 'subtotal')
    op.drop_column('order_items', 'product_image')
    op.drop_column('order_items', 'product_sku')
    op.drop_column('order_items', 'price')
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('deposit_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('remaining_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.alter_column('orders', 'shipping_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'payment_method',
               existing_type=postgresql.ENUM('COD', 'MOMO', 'VNPAY', 'BANK_TRANSFER', name='paymentmethod'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('orders', 'shipping_address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPING', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'),
               type_=sa.String(),
               nullable=True)
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.drop_column('orders', 'customer_email')
    op.drop_column('orders', 'order_number')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'shipping_district')
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'admin_notes')
    op.drop_column('orders', 'transaction_id')
    op.drop_column('orders', 'customer_notes')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'shipping_ward')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_ward', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('customer_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_district', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('payment_status', postgresql.ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=True)
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPING', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'),
               nullable=False)
    op.alter_column('orders', 'shipping_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.String(),
               type_=postgresql.ENUM('COD', 'MOMO', 'VNPAY', 'BANK_TRANSFER', name='paymentmethod'),
               nullable=False)
    op.alter_column('orders', 'shipping_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('orders', 'cancellation_reason')
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'full_name')
    op.drop_column('orders', 'is_paid')
    op.drop_column('orders', 'remaining_amount')
    op.drop_column('orders', 'deposit_amount')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'discount_amount')
    op.add_column('order_items', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('product_sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('product_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'variant')
    op.drop_column('order_items', 'price_at_purchase')
    # ### end Alembic commands ###
