"""add_coupon_table

Revision ID: 9a14795af9bb
Revises: 953b1ada8153
Create Date: 2025-12-02 06:08:58.017341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a14795af9bb'
down_revision: Union[str, None] = '953b1ada8153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_receipt_items_id', table_name='stock_receipt_items')
    op.drop_table('stock_receipt_items')
    op.drop_index('ix_stock_receipts_id', table_name='stock_receipts')
    op.drop_index('ix_stock_receipts_receipt_code', table_name='stock_receipts')
    op.drop_table('stock_receipts')
    op.drop_index('idx_unique_active_session_per_user', table_name='chat_sessions', postgresql_where="((status = 'ACTIVE'::chatstatus) AND (user_id IS NOT NULL))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unique_active_session_per_user', 'chat_sessions', ['user_id', 'status'], unique=True, postgresql_where="((status = 'ACTIVE'::chatstatus) AND (user_id IS NOT NULL))")
    op.create_table('stock_receipts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stock_receipts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('receipt_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('supplier_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('supplier_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='stockreceiptstatus'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='stock_receipts_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_receipts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stock_receipts_receipt_code', 'stock_receipts', ['receipt_code'], unique=True)
    op.create_index('ix_stock_receipts_id', 'stock_receipts', ['id'], unique=False)
    op.create_table('stock_receipt_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='stock_receipt_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['receipt_id'], ['stock_receipts.id'], name='stock_receipt_items_receipt_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_receipt_items_pkey')
    )
    op.create_index('ix_stock_receipt_items_id', 'stock_receipt_items', ['id'], unique=False)
    # ### end Alembic commands ###
